### ISSUE TITLE
The code in solver.py seems wrong.

### ISSUE THREAD

**Issue by poor1017** [jjery2243542/voice_conversion#20]
Hi @jjery2243542 

    Thank you for your code. When I read the code, I find there is something wrong:

For master branch:

No 'train' mode in function 'solver.Solver.train', but in main.py, I see the code 'solver.train(args.output_model_path, args.flag, mode='train')'.

Please have a check if you have time.

**Comment by josearangos** [comment]
Hello,

Dear friend
I want to speak with you about this repository, so that together we can run this experiment.
could you please give me your email. My email is: jose.arangos@udea.edu.co

Do you know how I can solve the Error in self.permute_data (data)?

I was trying to run the main.py file to retrain the model as you guided but in the middle of the process it threw an error "too many values to unpack (expected 2)" at line 279 in solver.py which is (c_i, c_j), (x_i_t, x_i_tk, x_i_prime, x_j) = self.permute_data(data).
Then I recognized that permute() function does not output many elements like this.

Did I miss something?
Can anybody help me out of it?

**Comment by josearangos** [comment]
this repository did not work but this one did

https://github.com/arshd91/multitarget-voice-conversion-vctk

**Comment by poor1017** [comment]
Hi @josearangos 

Actually, you can use the 'public' branch and you will get the pretty good results for English without any errors.
